### PR TITLE
Anki 2.1.61

### PR DESCRIPTION
**Pull request by mikehardy**
Update anki submodule to 2.1.61 SHA, bump release version

### CODE REVIEW

**Comment by mikehardy** [comment]
Hey @dae - sorry to bug you, but do you have any thoughts on this failure?

https://github.com/ankidroid/Anki-Android-Backend/actions/runs/4583618249/jobs/8094970289?pr=280

Is the build here doing some format checking and failing the build because it's unhappy about the current format?

**Comment by dae** [comment]
Updating rust-toolchain.toml to match the one in anki/ should fix it.

**Comment by mikehardy** [comment]
@dae confusing! it does not seem to have had any effect, similarly in CI as on my local windows dev environment where I'm testing.

It appears to see the file, with it's I-assume-correct version, overriding things:

```

PS C:\Users\micro\work\ankidroid\Anki-Android-Backend> rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\micro\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
1.65-x86_64-pc-windows-msvc
1.66.1-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

x86_64-linux-android
x86_64-pc-windows-msvc

active toolchain
----------------

1.66.1-x86_64-pc-windows-msvc (overridden by 'C:\Users\micro\work\ankidroid\Anki-Android-Backend\rust-toolchain.toml')
rustc 1.66.1 (90743e729 2023-01-10)
```

But if I do `check-rust.bat` it still throws that error.

I haven't been able to find any thing that looked exactly correct online about it yet :-(

**Comment by dae** [comment]
Ok, the problem here is that the desktop uses a nightly Rust for formatting/format checking as it has some extra features, but it appears in this case to disagree with stable Rust here. You can opt in to using the same nightly checker:

```
diff --git a/check-rust.sh b/check-rust.sh
index 88f28a0d3..f91bed811 100755
--- a/check-rust.sh
+++ b/check-rust.sh
@@ -2,6 +2,5 @@

 set -e

-rustup component add rustfmt clippy
-cargo clippy
-cargo fmt -- --check
+rustup component add clippy && cargo clippy
+(cd anki/cargo/format && cargo fmt --check --all --manifest-path ../../../Cargo.toml)
```

The .bat file will need similar changes

**Comment by mikehardy** [comment]
Great! Thank you

**Pull request merged**
