### PR TITLE
Ship mathjax and jquery

### PR DESCRIPTION
**Pull request by MorenoTropical**
* Fixes https://github.com/ankidroid/Anki-Android/issues/15138

### CODE REVIEW

**Comment by mikehardy** [comment]
If @BrayanDSO likes this then we should merge and publish

Note that ubuntu-24 is a new runner image for us (it just promoted to `ubuntu-latest` yesterday) so I expect that the "build quick" CI check on ubuntu may fail. That is not related to this PR and should not block it. See #422

**Comment by mikehardy** [comment]
I will unblock the codeql and build-quick:ubuntu CI runs by rebasing after #424 merges

But macos and windows should not fail, there appears to be an actual problem with the main.rs changes

```

Diff in /Users/runner/work/Anki-Android-Backend/Anki-Android-Backend/build_rust/src/main.rs at line 102:
         artifacts_dir.join("web/reviewer.css"),
     )?;
 
-    copy_dir_all("anki/out/qt/_aqt/data/web/js/vendor/mathjax", artifacts_dir.join("web/vendor/mathjax"))?;
+    copy_dir_all(
+        "anki/out/qt/_aqt/data/web/js/vendor/mathjax",
+        artifacts_dir.join("web/vendor/mathjax"),
+    )?;
     copy_file(
-            "anki/out/ts/mathjax/mathjax.js",
-            artifacts_dir.join("web/mathjax.js"),
-        )?;
+        "anki/out/ts/mathjax/mathjax.js",
+        artifacts_dir.join("web/mathjax.js"),
+    )?;
     copy_file(
         "anki/out/node_modules/jquery/dist/jquery.min.js",
         artifacts_dir.join("web/jquery.min.js"),
```

Did this build locally for you @MorenoTropical  ?

**Review by mikehardy — CHANGES_REQUESTED** [review]
style looks fine as a start (though may need to expose mathjax.css as well if it is in some specific location), but has an actual build failure

also needs a rebase to unblock CI once #424 is in

**Comment by mikehardy** [comment]
⚠️  I just re-pushed to unblock CI with #424 merged - it was after your push just now so should not have clobbered anything, we'll see how CI goes

**Comment by mikehardy** [comment]
Okay, ubuntu seems to be going through now after pinning to ubuntu-22 and you're last push

WIndows seems to have a platform-specific issue:

> Failed to execute: rsync --relative a11y/assisti.... etc

Two quick ideas:

- rsync not available by default on windows, I need to check runner image included software and see, install if not present
- platform-specific exec of rsync is failing (maybe needs to be "rsync.exe", maybe needs different directory seperators like \ instead of /

Some of the build stuff needed alteration prior because of platform-specific items, this may be another case of that, as these targets may never have been built on windows

**Review by BrayanDSO — COMMENTED** [review]
Anki references the files with a slightly different directory structure:

```html
<link rel="stylesheet" type="text/css" href="http://127.0.0.1:7981/_anki/css/reviewer.css">
...
<script src="http://127.0.0.1:7981/_anki/js/mathjax.js"></script>
<script src="http://127.0.0.1:7981/_anki/js/vendor/mathjax/tex-chtml-full.js"></script>
```

So while Anki has a `css/` and `js/` folder, we ship everything under `web/`.

`web/` was used originally for the Svelte pages, which were under `qt/_aqt/data/web` back then, so the name made sense.

As the Svelte pages are now shipped under `sveltekit/`, `web/` is mostly a legacy name.

To avoid some mental juggling about the directories names, I suggest to mimic Anki's directory tree structure.

Since this is just a refactor, that's not essential for approving the PR and doesn't need to be done right now.

**Review by BrayanDSO — APPROVED** [review]
> Failed to execute: rsync --relative a11y/assistive-mml.js a11y/complexity.js a11y/explorer.js a11y/semantic-enrich.js output/chtml/fonts/woff-v2/MathJax_AMS-Regular.woff output/chtml/fonts/woff-v2/MathJax_Calligraphic-Bold.woff output/chtml/fonts/woff-v2/MathJax_Calligraphic-Regular.woff output/chtml/fonts/woff-v2/MathJax_Fraktur-Bold.woff output/chtml/fonts/woff-v2/MathJax_Fraktur-Regular.woff output/chtml/fonts/woff-v2/MathJax_Main-Bold.woff output/chtml/fonts/woff-v2/MathJax_Main-Italic.woff output/chtml/fonts/woff-v2/MathJax_Main-Regular.woff output/chtml/fonts/woff-v2/MathJax_Math-BoldItalic.woff output/chtml/fonts/woff-v2/MathJax_Math-Italic.woff output/chtml/fonts/woff-v2/MathJax_Math-Regular.woff output/chtml/fonts/woff-v2/MathJax_SansSerif-Bold.woff output/chtml/fonts/woff-v2/MathJax_SansSerif-Italic.woff output/chtml/fonts/woff-v2/MathJax_SansSerif-Regular.woff output/chtml/fonts/woff-v2/MathJax_Script-Regular.woff output/chtml/fonts/woff-v2/MathJax_Size1-Regular.woff output/chtml/fonts/woff-v2/MathJax_Size2-Regular.woff output/chtml/fonts/woff-v2/MathJax_Size3-Regular.woff output/chtml/fonts/woff-v2/MathJax_Size4-Regular.woff output/chtml/fonts/woff-v2/MathJax_Typewriter-Regular.woff output/chtml/fonts/woff-v2/MathJax_Vector-Bold.woff output/chtml/fonts/woff-v2/MathJax_Vector-Regular.woff output/chtml/fonts/woff-v2/MathJax_Zero.woff tex-chtml-full.js sre/mathmaps/de.json sre/mathmaps/en.json sre/mathmaps/es.json sre/mathmaps/fr.json sre/mathmaps/hi.json sre/mathmaps/it.json sre/mathmaps/nemeth.json /D/a/Anki-Android-Backend/Anki-Android-Backend/anki/out/qt/_aqt/data/web/js/vendor/mathjax


I managed to built it in my Windows machine. Can't tell why this is happening

**Comment by MorenoTropical** [comment]
> To avoid some mental juggling about the directories names, I suggest to mimic Anki's directory tree structure.

Done

**Comment by mikehardy** [comment]
just added the commit that should get windows working in CI ? 🤞 

The path changes look good to me - I'm sorry to ping you Brayan, I don't do it lightly - but I also know you have strong + good opinions in this specific area so with the paths changed now, I think it's good for you to have a look before they're shipped with new paths...

**Review by BrayanDSO — APPROVED** [review]
Nice! Thanks

**Review by mikehardy — APPROVED** [review]
everything appears to be working well no on windows ✅ 
everything else has been thoroughly reviewed ✅

**Pull request merged**
