### PR TITLE
Add backend exception for invalid certificates

### PR DESCRIPTION
**Pull request by voczi**
Related PR https://github.com/ankitects/anki/pull/3203

### CODE REVIEW

**Comment by voczi** [comment]
Checked the workflows on my fork, seems like the recent Svelte changes in the backend is causing build errors.

**Review by mikehardy — COMMENTED** [review]
this does look like what I would expect - just one clean commit
But I recognize it *may* depend on the backend anki submodule update that I requested you remove, so I told CI to chew on it but of course it might explode spectacularly since it doesn't have that update

That just means the other PR needs to go in first, which is fine

**Comment by mikehardy** [comment]
Thanks by the way! Have been distracted and just in "robot review" mode, but I appreciate the PR :-)

**Comment by voczi** [comment]
No worries. Seen you guys been busy with Ankidroid development 🙂

**Comment by mikehardy** [comment]
As expected - going to say this is just blocked on #381 

> e: file:///home/runner/work/Anki-Android-Backend/Anki-Android-Backend/rsdroid/src/main/java/net/ankiweb/rsdroid/BackendException.kt:128:35 Unresolved reference: INVALID_CERTIFICATE_FORMAT

**Comment by voczi** [comment]
It's added in the PR now https://github.com/ankidroid/Anki-Android-Backend/pull/381

**Pull request closed without merging**
